import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import vm from "node:vm";

const adapter = vm.createContext({});
vm.runInContext(readFileSync(new URL("../Common/AqueousDisplays.js", import.meta.url), "utf8").replace(".pragma library", ""), adapter);
const mode = {id: "mode", width: 1920, height: 1080, refresh: 59940};
const output = {id: "head", name: "DP-1", enabled: true, x: -1920, y: 0, scale: 1, transform: 0, modes: [mode], currentMode: mode};
const original = [output];
const candidate = adapter.heads(original);
assert.equal(adapter.matches(candidate, original, original), true);
assert.equal(adapter.matches(candidate, [{...output, id: "recreated"}], original), false);
assert.equal(adapter.matches(candidate, [{...output, scale: 1.25}], original), false);
assert.equal(adapter.matches(candidate, [], original), false);
assert.notEqual(adapter.fingerprint(original), adapter.fingerprint([{...output, x: 0}]));
assert.equal(adapter.fingerprint([output, {...output, id: "head2", name: "DP-2"}]), adapter.fingerprint([{...output, id: "head2", name: "DP-2"}, output]));
const snapshot = {capabilities: ["monitor_modes"], generation: "generation", monitors: [{id: "output:0", name: "DP-1", scale: 1}, {id: "output:1", name: "offline", scale: 2}]};
const request = adapter.request(snapshot, original, original);
assert.equal(request.expected_generation, "generation");
assert.equal(request.monitor_changes.length, 1);
assert.equal(request.monitor_changes[0].mode, "1920x1080@59.94");
assert.equal(request.monitor_changes[0].x, -1920);
assert.throws(() => adapter.request(snapshot, [{...output, scale: 1.25}], original), /scale/);
assert.throws(() => adapter.request(snapshot, [{...output, enabled: false}], original), /enablement/);
assert.throws(() => adapter.request({...snapshot, raw_files: {outputs: '[[output]]\nedid = "sha256:test"'}}, original, original), /EDID/);
assert.throws(() => adapter.request({...snapshot, capabilities: []}, original, original), /unsupported/);
process.stdout.write("PASS: Aqueous display identity, conflicts, offline preservation and helper limits\n");
