// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_network

import (
	"github.com/AvengeMedia/DankMaterialShell/core/internal/server/network"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionEditorBackend creates a new instance of MockConnectionEditorBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionEditorBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionEditorBackend {
	mock := &MockConnectionEditorBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionEditorBackend is an autogenerated mock type for the ConnectionEditorBackend type
type MockConnectionEditorBackend struct {
	mock.Mock
}

type MockConnectionEditorBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionEditorBackend) EXPECT() *MockConnectionEditorBackend_Expecter {
	return &MockConnectionEditorBackend_Expecter{mock: &_m.Mock}
}

// ActivateConnectionProfile provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) ActivateConnectionProfile(uuid string, device string) error {
	ret := _mock.Called(uuid, device)

	if len(ret) == 0 {
		panic("no return value specified for ActivateConnectionProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(uuid, device)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionEditorBackend_ActivateConnectionProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateConnectionProfile'
type MockConnectionEditorBackend_ActivateConnectionProfile_Call struct {
	*mock.Call
}

// ActivateConnectionProfile is a helper method to define mock.On call
//   - uuid string
//   - device string
func (_e *MockConnectionEditorBackend_Expecter) ActivateConnectionProfile(uuid any, device any) *MockConnectionEditorBackend_ActivateConnectionProfile_Call {
	return &MockConnectionEditorBackend_ActivateConnectionProfile_Call{Call: _e.mock.On("ActivateConnectionProfile", uuid, device)}
}

func (_c *MockConnectionEditorBackend_ActivateConnectionProfile_Call) Run(run func(uuid string, device string)) *MockConnectionEditorBackend_ActivateConnectionProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_ActivateConnectionProfile_Call) Return(err error) *MockConnectionEditorBackend_ActivateConnectionProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionEditorBackend_ActivateConnectionProfile_Call) RunAndReturn(run func(uuid string, device string) error) *MockConnectionEditorBackend_ActivateConnectionProfile_Call {
	_c.Call.Return(run)
	return _c
}

// AddConnectionProfile provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) AddConnectionProfile(settings network.SettingsPatch, persist bool) (string, error) {
	ret := _mock.Called(settings, persist)

	if len(ret) == 0 {
		panic("no return value specified for AddConnectionProfile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(network.SettingsPatch, bool) (string, error)); ok {
		return returnFunc(settings, persist)
	}
	if returnFunc, ok := ret.Get(0).(func(network.SettingsPatch, bool) string); ok {
		r0 = returnFunc(settings, persist)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(network.SettingsPatch, bool) error); ok {
		r1 = returnFunc(settings, persist)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionEditorBackend_AddConnectionProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddConnectionProfile'
type MockConnectionEditorBackend_AddConnectionProfile_Call struct {
	*mock.Call
}

// AddConnectionProfile is a helper method to define mock.On call
//   - settings network.SettingsPatch
//   - persist bool
func (_e *MockConnectionEditorBackend_Expecter) AddConnectionProfile(settings any, persist any) *MockConnectionEditorBackend_AddConnectionProfile_Call {
	return &MockConnectionEditorBackend_AddConnectionProfile_Call{Call: _e.mock.On("AddConnectionProfile", settings, persist)}
}

func (_c *MockConnectionEditorBackend_AddConnectionProfile_Call) Run(run func(settings network.SettingsPatch, persist bool)) *MockConnectionEditorBackend_AddConnectionProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 network.SettingsPatch
		if args[0] != nil {
			arg0 = args[0].(network.SettingsPatch)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_AddConnectionProfile_Call) Return(s string, err error) *MockConnectionEditorBackend_AddConnectionProfile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConnectionEditorBackend_AddConnectionProfile_Call) RunAndReturn(run func(settings network.SettingsPatch, persist bool) (string, error)) *MockConnectionEditorBackend_AddConnectionProfile_Call {
	_c.Call.Return(run)
	return _c
}

// CheckConnectivity provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) CheckConnectivity() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckConnectivity")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionEditorBackend_CheckConnectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckConnectivity'
type MockConnectionEditorBackend_CheckConnectivity_Call struct {
	*mock.Call
}

// CheckConnectivity is a helper method to define mock.On call
func (_e *MockConnectionEditorBackend_Expecter) CheckConnectivity() *MockConnectionEditorBackend_CheckConnectivity_Call {
	return &MockConnectionEditorBackend_CheckConnectivity_Call{Call: _e.mock.On("CheckConnectivity")}
}

func (_c *MockConnectionEditorBackend_CheckConnectivity_Call) Run(run func()) *MockConnectionEditorBackend_CheckConnectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionEditorBackend_CheckConnectivity_Call) Return(s string, err error) *MockConnectionEditorBackend_CheckConnectivity_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConnectionEditorBackend_CheckConnectivity_Call) RunAndReturn(run func() (string, error)) *MockConnectionEditorBackend_CheckConnectivity_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateConnectionProfile provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) DeactivateConnectionProfile(uuid string) error {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateConnectionProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionEditorBackend_DeactivateConnectionProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateConnectionProfile'
type MockConnectionEditorBackend_DeactivateConnectionProfile_Call struct {
	*mock.Call
}

// DeactivateConnectionProfile is a helper method to define mock.On call
//   - uuid string
func (_e *MockConnectionEditorBackend_Expecter) DeactivateConnectionProfile(uuid any) *MockConnectionEditorBackend_DeactivateConnectionProfile_Call {
	return &MockConnectionEditorBackend_DeactivateConnectionProfile_Call{Call: _e.mock.On("DeactivateConnectionProfile", uuid)}
}

func (_c *MockConnectionEditorBackend_DeactivateConnectionProfile_Call) Run(run func(uuid string)) *MockConnectionEditorBackend_DeactivateConnectionProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_DeactivateConnectionProfile_Call) Return(err error) *MockConnectionEditorBackend_DeactivateConnectionProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionEditorBackend_DeactivateConnectionProfile_Call) RunAndReturn(run func(uuid string) error) *MockConnectionEditorBackend_DeactivateConnectionProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConnectionProfile provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) DeleteConnectionProfile(uuid string) error {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnectionProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionEditorBackend_DeleteConnectionProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnectionProfile'
type MockConnectionEditorBackend_DeleteConnectionProfile_Call struct {
	*mock.Call
}

// DeleteConnectionProfile is a helper method to define mock.On call
//   - uuid string
func (_e *MockConnectionEditorBackend_Expecter) DeleteConnectionProfile(uuid any) *MockConnectionEditorBackend_DeleteConnectionProfile_Call {
	return &MockConnectionEditorBackend_DeleteConnectionProfile_Call{Call: _e.mock.On("DeleteConnectionProfile", uuid)}
}

func (_c *MockConnectionEditorBackend_DeleteConnectionProfile_Call) Run(run func(uuid string)) *MockConnectionEditorBackend_DeleteConnectionProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_DeleteConnectionProfile_Call) Return(err error) *MockConnectionEditorBackend_DeleteConnectionProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionEditorBackend_DeleteConnectionProfile_Call) RunAndReturn(run func(uuid string) error) *MockConnectionEditorBackend_DeleteConnectionProfile_Call {
	_c.Call.Return(run)
	return _c
}

// DuplicateConnectionProfile provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) DuplicateConnectionProfile(uuid string, name string) (string, error) {
	ret := _mock.Called(uuid, name)

	if len(ret) == 0 {
		panic("no return value specified for DuplicateConnectionProfile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(uuid, name)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(uuid, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(uuid, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionEditorBackend_DuplicateConnectionProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DuplicateConnectionProfile'
type MockConnectionEditorBackend_DuplicateConnectionProfile_Call struct {
	*mock.Call
}

// DuplicateConnectionProfile is a helper method to define mock.On call
//   - uuid string
//   - name string
func (_e *MockConnectionEditorBackend_Expecter) DuplicateConnectionProfile(uuid any, name any) *MockConnectionEditorBackend_DuplicateConnectionProfile_Call {
	return &MockConnectionEditorBackend_DuplicateConnectionProfile_Call{Call: _e.mock.On("DuplicateConnectionProfile", uuid, name)}
}

func (_c *MockConnectionEditorBackend_DuplicateConnectionProfile_Call) Run(run func(uuid string, name string)) *MockConnectionEditorBackend_DuplicateConnectionProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_DuplicateConnectionProfile_Call) Return(s string, err error) *MockConnectionEditorBackend_DuplicateConnectionProfile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConnectionEditorBackend_DuplicateConnectionProfile_Call) RunAndReturn(run func(uuid string, name string) (string, error)) *MockConnectionEditorBackend_DuplicateConnectionProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ExportConnectionProfile provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) ExportConnectionProfile(uuid string, path string) error {
	ret := _mock.Called(uuid, path)

	if len(ret) == 0 {
		panic("no return value specified for ExportConnectionProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(uuid, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionEditorBackend_ExportConnectionProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportConnectionProfile'
type MockConnectionEditorBackend_ExportConnectionProfile_Call struct {
	*mock.Call
}

// ExportConnectionProfile is a helper method to define mock.On call
//   - uuid string
//   - path string
func (_e *MockConnectionEditorBackend_Expecter) ExportConnectionProfile(uuid any, path any) *MockConnectionEditorBackend_ExportConnectionProfile_Call {
	return &MockConnectionEditorBackend_ExportConnectionProfile_Call{Call: _e.mock.On("ExportConnectionProfile", uuid, path)}
}

func (_c *MockConnectionEditorBackend_ExportConnectionProfile_Call) Run(run func(uuid string, path string)) *MockConnectionEditorBackend_ExportConnectionProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_ExportConnectionProfile_Call) Return(err error) *MockConnectionEditorBackend_ExportConnectionProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionEditorBackend_ExportConnectionProfile_Call) RunAndReturn(run func(uuid string, path string) error) *MockConnectionEditorBackend_ExportConnectionProfile_Call {
	_c.Call.Return(run)
	return _c
}

// FirewallZones provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) FirewallZones() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FirewallZones")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionEditorBackend_FirewallZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirewallZones'
type MockConnectionEditorBackend_FirewallZones_Call struct {
	*mock.Call
}

// FirewallZones is a helper method to define mock.On call
func (_e *MockConnectionEditorBackend_Expecter) FirewallZones() *MockConnectionEditorBackend_FirewallZones_Call {
	return &MockConnectionEditorBackend_FirewallZones_Call{Call: _e.mock.On("FirewallZones")}
}

func (_c *MockConnectionEditorBackend_FirewallZones_Call) Run(run func()) *MockConnectionEditorBackend_FirewallZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionEditorBackend_FirewallZones_Call) Return(strings []string, err error) *MockConnectionEditorBackend_FirewallZones_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockConnectionEditorBackend_FirewallZones_Call) RunAndReturn(run func() ([]string, error)) *MockConnectionEditorBackend_FirewallZones_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionSettings provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) GetConnectionSettings(uuid string, withSecrets bool) (map[string]map[string]any, error) {
	ret := _mock.Called(uuid, withSecrets)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionSettings")
	}

	var r0 map[string]map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (map[string]map[string]any, error)); ok {
		return returnFunc(uuid, withSecrets)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) map[string]map[string]any); ok {
		r0 = returnFunc(uuid, withSecrets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(uuid, withSecrets)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionEditorBackend_GetConnectionSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionSettings'
type MockConnectionEditorBackend_GetConnectionSettings_Call struct {
	*mock.Call
}

// GetConnectionSettings is a helper method to define mock.On call
//   - uuid string
//   - withSecrets bool
func (_e *MockConnectionEditorBackend_Expecter) GetConnectionSettings(uuid any, withSecrets any) *MockConnectionEditorBackend_GetConnectionSettings_Call {
	return &MockConnectionEditorBackend_GetConnectionSettings_Call{Call: _e.mock.On("GetConnectionSettings", uuid, withSecrets)}
}

func (_c *MockConnectionEditorBackend_GetConnectionSettings_Call) Run(run func(uuid string, withSecrets bool)) *MockConnectionEditorBackend_GetConnectionSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_GetConnectionSettings_Call) Return(stringToStringToAnyMoqParam map[string]map[string]any, err error) *MockConnectionEditorBackend_GetConnectionSettings_Call {
	_c.Call.Return(stringToStringToAnyMoqParam, err)
	return _c
}

func (_c *MockConnectionEditorBackend_GetConnectionSettings_Call) RunAndReturn(run func(uuid string, withSecrets bool) (map[string]map[string]any, error)) *MockConnectionEditorBackend_GetConnectionSettings_Call {
	_c.Call.Return(run)
	return _c
}

// ListConnectionProfiles provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) ListConnectionProfiles() ([]network.ConnectionProfile, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListConnectionProfiles")
	}

	var r0 []network.ConnectionProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]network.ConnectionProfile, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []network.ConnectionProfile); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]network.ConnectionProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionEditorBackend_ListConnectionProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConnectionProfiles'
type MockConnectionEditorBackend_ListConnectionProfiles_Call struct {
	*mock.Call
}

// ListConnectionProfiles is a helper method to define mock.On call
func (_e *MockConnectionEditorBackend_Expecter) ListConnectionProfiles() *MockConnectionEditorBackend_ListConnectionProfiles_Call {
	return &MockConnectionEditorBackend_ListConnectionProfiles_Call{Call: _e.mock.On("ListConnectionProfiles")}
}

func (_c *MockConnectionEditorBackend_ListConnectionProfiles_Call) Run(run func()) *MockConnectionEditorBackend_ListConnectionProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectionEditorBackend_ListConnectionProfiles_Call) Return(connectionProfiles []network.ConnectionProfile, err error) *MockConnectionEditorBackend_ListConnectionProfiles_Call {
	_c.Call.Return(connectionProfiles, err)
	return _c
}

func (_c *MockConnectionEditorBackend_ListConnectionProfiles_Call) RunAndReturn(run func() ([]network.ConnectionProfile, error)) *MockConnectionEditorBackend_ListConnectionProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// SetConnectivityCheckEnabled provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) SetConnectivityCheckEnabled(enabled bool) error {
	ret := _mock.Called(enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetConnectivityCheckEnabled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(bool) error); ok {
		r0 = returnFunc(enabled)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConnectivityCheckEnabled'
type MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call struct {
	*mock.Call
}

// SetConnectivityCheckEnabled is a helper method to define mock.On call
//   - enabled bool
func (_e *MockConnectionEditorBackend_Expecter) SetConnectivityCheckEnabled(enabled any) *MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call {
	return &MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call{Call: _e.mock.On("SetConnectivityCheckEnabled", enabled)}
}

func (_c *MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call) Run(run func(enabled bool)) *MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call) Return(err error) *MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call) RunAndReturn(run func(enabled bool) error) *MockConnectionEditorBackend_SetConnectivityCheckEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConnectionSettings provides a mock function for the type MockConnectionEditorBackend
func (_mock *MockConnectionEditorBackend) UpdateConnectionSettings(uuid string, patch network.SettingsPatch, persist bool) error {
	ret := _mock.Called(uuid, patch, persist)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnectionSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, network.SettingsPatch, bool) error); ok {
		r0 = returnFunc(uuid, patch, persist)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionEditorBackend_UpdateConnectionSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnectionSettings'
type MockConnectionEditorBackend_UpdateConnectionSettings_Call struct {
	*mock.Call
}

// UpdateConnectionSettings is a helper method to define mock.On call
//   - uuid string
//   - patch network.SettingsPatch
//   - persist bool
func (_e *MockConnectionEditorBackend_Expecter) UpdateConnectionSettings(uuid any, patch any, persist any) *MockConnectionEditorBackend_UpdateConnectionSettings_Call {
	return &MockConnectionEditorBackend_UpdateConnectionSettings_Call{Call: _e.mock.On("UpdateConnectionSettings", uuid, patch, persist)}
}

func (_c *MockConnectionEditorBackend_UpdateConnectionSettings_Call) Run(run func(uuid string, patch network.SettingsPatch, persist bool)) *MockConnectionEditorBackend_UpdateConnectionSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 network.SettingsPatch
		if args[1] != nil {
			arg1 = args[1].(network.SettingsPatch)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectionEditorBackend_UpdateConnectionSettings_Call) Return(err error) *MockConnectionEditorBackend_UpdateConnectionSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionEditorBackend_UpdateConnectionSettings_Call) RunAndReturn(run func(uuid string, patch network.SettingsPatch, persist bool) error) *MockConnectionEditorBackend_UpdateConnectionSettings_Call {
	_c.Call.Return(run)
	return _c
}
